php:
  version: 
    - '5.5.16'
    - '5.6'
    - '7.0'
hooks:
  pre_setup: composer install
tests:
  - ./vendor/bin/phpunit
cache:
  key_paths:
    - composer.json
    - composer.lock
  save_paths:
    - vendor